substitutions:
  name: "wifi_ac_energy_meter"
  friendly_name: "XIAO 2 Channel Wi-Fi AC Energy Meter"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  on_boot: 
    priority: 100
    then:
      - output.turn_on: gpio_14_output
      # - output.turn_off: led_light
      # - light.turn_on: led_light
      # - delay: 10s  
      # - light.turn_off: led_staus

output:
  - platform: gpio
    pin: GPIO14
    id: gpio_14_output
  - platform: gpio
    pin: GPIO19
    id: led_light
    inverted: true

light:
  - platform: binary
    name: "status LED"
    output: led_light
    restore_mode: ALWAYS_ON

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB    
  framework:
    type: esp-idf
    


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  # output_power: 20dB
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  # on_connect:
  #     then:
  #       - light.turn_on: led_staus

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "xiao_wifi_ac_energy_meter"

captive_portal:

web_server:
  port: 80

external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/Seeed-Studio/xiao-esphome-projects
      ref: main
    components: [ bl0939 ]
    refresh: 0s  

uart:
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 4800

sensor:
  - platform: bl0939
    mode: 'current_transformer_mode'

    voltage:
      name: 'BL0939 Voltage'
    current_1:
      name: 'BL0939 Current 1'
    current_2:
      name: 'BL0939 Current 2'
    active_power_1:
      name: 'BL0939 Active Power 1'
    active_power_2:
      name: 'BL0939 Active Power 2'
    energy_1:
      name: 'BL0939 Energy 1'
    energy_2:
      name: 'BL0939 Energy 2'
    energy_total:
      name: 'BL0939 Energy Total'

    update_interval: 15s
    
  - platform: wifi_signal
    name: "wifi singnal strength"
    update_interval: 10s

# light:
#   - platform: status_led
#     id: led_staus
#     name: "Switch state"
#     pin:
#       number:  GPIO19
#       inverted: true